### ISSUE TITLE
Using iOS 8.4, app crashes when accessing previously saved Core Data object

### ISSUE THREAD

**Issue by tfrank64** [mkistler/CDTIS_iPhoneCoreDataRecipes#2]
To reproduce, run the sample app on iOS 8.4, create a recipe, sync with server. Restart application, and access a previously created recipe and the app should crash with the following error:

```
*** Terminating app due to uncaught exception 'NSObjectInaccessibleException', reason: 'CoreData could not fulfill a fault for '0x7f96e1552d80 <x-coredata://CDTIS-NSStore-0E78DED5-45DD-41C0-B9CC-F1F1B1D2F99F/RecipeType/p>''
```

**Comment by mkistler** [comment]
I have recreated this problem, and it does not appear to be iOS-version specific, since it also happens with the iOS 8.1 simulator.

**Comment by mkistler** [comment]
According to (this blog post](http://commandshift.co.uk/blog/2013/06/06/multiple-persistent-stores-in-core-data/): "You can't make relationships between entities in different stores."

The link to the doc in this post is broken, but the [latest doc](https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/CoreData/HowManagedObjectsarerelated.html#//apple_ref/doc/uid/TP40001075-CH17-SW1) contains essentially the same admonition:

**Cross-Store Relationships Not Supported**

Be careful not to create relationships from instances in one persistent store to instances in another persistent store, as this is not supported by Core Data. If you need to create a relationship between entities in different stores, you typically use fetched properties.

So the "two persistent store" version of the app is broken because it violates this rule -- it creates relationships between new recipes (in the CDT store) and RecipeTypes (in the SQLite store).

**Comment by mkistler** [comment]
Closing old issue.
